urls.py
from django.conf.urls.defaults import patterns, include, url
from django.utils.translation import ugettext_lazy as _
from django.http import HttpResponse


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from admin import *
from app.views import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /config\nDisallow: /done", mimetype="text/plain")),
    url(r'', include('app.urls')),
    url(r'', include('social_auth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

app/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from social_auth.models import UserSocialAuth
from datetime import datetime,timedelta
from django_fields.tests import EncryptedCharField
from django.core.mail import EmailMultiAlternatives
from django.utils.translation import ugettext as _
from django.shortcuts import render
from app.utils import send_email_mandrill, connect_tweepy
from django.template.loader import render_to_string

import twitter
import tweepy

#from django.db.models.signals import post_save
#from django.dispatch import receiver

# Define a custom User class to work with django-social-auth
class CustomUserManager(models.Manager):
    def create_user(self, username, email):
        return self.model._default_manager.create(username=username)


class CustomUser(models.Model):
    configured = models.BooleanField(default=False)
    user = models.OneToOneField(UserSocialAuth)
    username = models.CharField(max_length=128)
    photo = models.URLField(blank=True, null=True)
    language = models.CharField(max_length=128, default='en', blank=True)
    #timezone = models.CharField(max_length=128, default='Europe/Madrid', blank=True)
    #countrycode = models.CharField(max_length=4, default='ES', blank=True)

    last_login = models.DateTimeField(blank=True, null=True)
    
    email = models.EmailField(blank=True)

    #intervalo de periodo de inactividad para considerar al usuario muerto/medio-muerto (segun si email ping o no)
    activity_interval = models.IntegerField(choices=settings.ACTIVITY_CHOICES, default=2419200, blank=False)
    
    #intervalo de tiempo entre emisiones de tweets una vez muerto
    publish_interval = models.IntegerField(choices=settings.PUBLISH_CHOICES, default=0, blank=False)

    #tiempo a esperar desde half-dead hasta dead
    mail_interval = models.IntegerField(choices=settings.ACTIVITY_CHOICES, default=1209600, blank=False)
    
    #fecha de la última publicación en twitter
    last_update = models.DateTimeField(blank=True, null=True)
    
    #fecha para la siguiente comprobación del estado de twitter
    next_check = models.DateTimeField(blank=True, null=True)
    
    #fecha para la siguiente envío de un post-tweet con interval_mail > 0
    next_check_mail = models.DateTimeField(blank=True, null=True)
    
    #if (now() - last_update) > activity_interval: 
	#half_dead = True
    half_dead = models.BooleanField(default=False)
    dead = models.BooleanField(default=False)

    #if we are waiting for a mail ping
    wait_mail = models.BooleanField(default=False)
    
    new_posttweet = models.BooleanField(default=False)
    
    #For the ask in the modal
    neverupdate = models.BooleanField(default=False)
    alwaysupdate = models.BooleanField(default=False)
    nottodayupdate = models.DateTimeField(blank=True, null=True)

    posts = models.IntegerField(default=0, blank=True, null=True)
    posts_sended = models.IntegerField(default=0, blank=True, null=True)
        
    objects = CustomUserManager()
    
    #def save(self, *args, **kwargs):
        #if not self.pk:
            #if not self.last_update:
                #self.update_date()
            #if not self.photo:
                #self.update_twitter_photo()
        #super(CustomUser, self).save(*args, **kwargs)
        

    def update_date(self, force=False):
	"Save the last update date in twitter for the user"
        api = twitter.Api(settings.TWITTER_CONSUMER_KEY,settings.TWITTER_CONSUMER_SECRET,settings.ACCESS_TOKEN,settings.ACCESS_TOKEN_SECRET)
        statuses = api.GetUserTimeline(self.username, count=1)
        if len(statuses) > 0:
            new_date = datetime.utcfromtimestamp(statuses[0].created_at_in_seconds)
        else:
            new_date = datetime.utcnow()
        
        if not self.activity_interval:
            self.activity_interval = 3600
        next_check = new_date + timedelta(seconds=self.activity_interval)            
        
        if not self.last_update or (self.last_update < new_date) or force:
            if force:
                self.last_update = datetime.utcnow()
                self.next_check = datetime.utcnow() + timedelta(seconds=self.activity_interval)
            else:
                self.last_update = new_date
                self.next_check = next_check
            self.save()
        return self.last_update
        
    def update_login_date(self):
        ##Checkin login in last day to update last_login, used in tasks
        if not self.last_login or self.last_login < (datetime.utcnow() - timedelta(seconds=settings.TIME_LOGIN)):
            self.last_login = datetime.utcnow()
            self.next_check = datetime.utcnow() + timedelta(seconds=self.activity_interval)
            self.save()

    def update_twitter_status(self, text):
	if text:
            api = connect_tweepy(self.user)
	    api.update_status(text)

    def update_twitter_photo(self):
        api = connect_tweepy(self.user)
        user = api.get_user(self.username)
        self.photo = user.profile_image_url
        self.save()
	    
    def get_twitter_friends(self):
        api = connect_tweepy(self.user)
        friends =[]
        for friend in tweepy.Cursor(api.friends).items():
            friends.append(friend.screen_name)
        return friends
        

    def show_modal_new_tweet(self):
	if self.alwaysupdate:
	    return False
	if self.neverupdate:
	    return False
	if self.nottodayupdate and (self.nottodayupdate > (datetime.utcnow() - timedelta(days=1))):
	    return False
	return True

    def bigger_date(self):
        if self.last_update < self.last_login:
            return self.last_login
        else:
            return self.last_update
	
    def send_email(self, subject,  html_content):
        send_email_mandrill(subject, html_content,settings.EMAIL_PROJECT ,settings.NAME_PROJECT,self.email, self.username)

    def number_posts(self):
        return Tweet.objects.filter(user=self).count()

    def send_email_halfdead(self):
	subject = _("Are you still alive?")
	
	html_content = render_to_string('half_dead.html', 
            { 
            'userlanguage': self.language,
            'username': self.username,
            'time_without_update': self.bigger_date(),
            'half_dead_time_mail_interval': self.bigger_date() + timedelta(seconds=(self.activity_interval+self.mail_interval)),
            'number_posts': self.number_posts(),
            'link_for_config': 'http://www.foowill.com/config'
            }
	)

	self.send_email(subject, html_content)
	
    def send_email_still_alive(self):
        subject = _("We are glad you are okay!")
        
        html_content = render_to_string('still_alive.html', 
            { 
            'username': self.username,
            'userlanguage': self.language,
            }
        )

        self.send_email(subject, html_content)

    def send_email_hope_to_read(self):
        subject = _("The time interval waiting for your twitter status update is exceeded")
        
        html_content = render_to_string('hope_to_read.html', 
            { 
            'username': self.username,
            'userlanguage': self.language,
            }
        )

        self.send_email(subject, html_content)
        
    def deliver_all_to_twitter(self):
        tweets = Tweet.objects.filter(user=self)
        for tweet in tweets:
            self.update_twitter_status(tweet.text)

    def deliver_one_to_twitter(self):    
        if self.posts_sended > 0:
            self.next_check_mail = datetime.utcnow() + timedelta(seconds=self.mail_interval)
            ts = self.posts - self.posts_sended
            self.posts_sended = self.posts_sended - 1
            tweets = Tweet.objects.filter(user=self)
            self.update_twitter_status(tweets[ts].text)
            self.save()
            
    def admin_thumbnail(self):
        return u'<img src="%s" />' % (self.photo)
    admin_thumbnail.short_description = 'Thumbnail'
    admin_thumbnail.allow_tags = True
    
    def admin_posts(self):
        return u'<a href="/admin/app/tweet/?q=1&user__id__exact=%d">%d Post-tweets</a>' % (self.id, self.posts)
    admin_posts.short_description = 'Post-tweets'
    admin_posts.allow_tags = True
    
    def is_authenticated(self):
        return True
    
    def __unicode__(self):
        return self.username
        
# Define Tweet 
class Tweet(models.Model):
    text = EncryptedCharField(max_length=140, unique=True, blank=False)
    user = models.ForeignKey(CustomUser)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.text

#@receiver(post_save, sender=CustomUser)
#def init_user(sender, instance, created, **kwargs):
    #"""Create a matching profile whenever a user object is created."""
    #if created: 
        #instance.update_twitter_photo()
        #instance.update_date()
        ##profile, new = UserProfile.objects.get_or_create(user=instance)

        
from social_auth.signals import pre_update
from social_auth.backends.facebook import FacebookBackend


def facebook_extra_values(sender, user, response, details, **kwargs):
    return False

pre_update.connect(facebook_extra_values, sender=FacebookBackend)

templates/about.html
    {% extends "base.html" %}

{% load i18n %}

{% block meta %}
  <meta property="og:title" content="Foowill" />
  <meta property="og:url" content="http://foowill.com" />
  <meta property="og:image" content="http://foowill.com/static/img/icon.jpg" />
  <meta property="og:site_name" content="foowill.com" />
{% endblock %}

{% block content %}

    {% include "user-box.html" %}

    <div class='main-box'>
        <div class='row-fluid home-initial-text'>
            <div class="span12">
                <div class="row-fluid">
                    <div class="span8">
                        <h3>{% trans "About Ba" %}</h3>
                        {% blocktrans %}
                        <p>Ba is a psychic strength, component of man's spiritual part, the animated strength of each deceased, spiritual personality manifested once death happened, according to Egyptian mythology.</p>
                        <p>It is a concept which refers to deceased man not to the alive one. Ba was a kind of mediator between gods and the earth, as it had mobility and it made possible that both worlds were connected. It was the way the deceased had for shifting and joining its ka which remained in the tomb.</p>
                        <p>Ba quitted the body when the person died and ascended to the celestial kingdom but, every night, it should come up to the tomb to lodge the deceased's body, it came and went from the gods' world to the tomb.</p>
                        <p>We chose Ba as a mascot in order to, as the Egyptians believed, carry a part of you when you are gone.</p>
                        <p><a href="http://www.egyptianmyths.net/ba.htm">More info</a></p>

                        {% endblocktrans %}
                    </div>
                    <div class="span4">
                        <img src='/static/img/foowill_color.jpeg'> 
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if not user.configured %}
         {% include "footer.html" %}
    {% endif %}

{% endblock %}

templates/base.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Foowill, tweets post-mortem</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content='{% trans "Foowill is an twitter application where you can save tweets that will be sent to your account when you die (post-tweets)." %}'>
    <meta name="keywords" content="post-mortem,die,tweet,twitter,app,last,will,muerte,webapp,words,save,mensaje,póstumo,mensajes,póstumos">
    <meta name="author" content="Foowill">
    <link rel='shortcut icon' href='/static/img/favicon.ico' type='image/x-icon'/>

    {% block meta %}{% endblock %}

    <!-- Less styles -->
    <link href="/static/css/flags.css" rel="stylesheet">

    {% block css %}{% endblock %}

    {% if DEBUG %}
        <link rel="stylesheet/less" type="text/css" href="/static/css/less/bootstrap.less">
        <link rel="stylesheet/less" type="text/css" href="/static/css/less/responsive.less">
        <link rel="stylesheet/less" type="text/css" href="/static/css/lessless.css">
        <script src="/static/js/less.js" type="text/javascript"></script>
    {% else %}
        <link href="/static/css/bootstrap.css" rel="stylesheet">
        <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/static/css/final.css" rel="stylesheet">
    {% endif %}

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Google analitycs -->
    <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32608311-1']);
    _gaq.push(['_trackPageview']);
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    </script>

    {% block head %}{% endblock %}
    
  </head>

    <body>
    {% load extras %}
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="/">Foowill</a>
            <ul class="nav">
              <li class="{% add_active request 'home' %}"><a href="/">{% trans "Home" %}</a></li>
              <li class="{% add_active request 'contact' %}"><a href="/contact">{% trans "Contact" %}</a></li>
            </ul>

            <ul class="nav pull-right">
              <li class="divider-vertical"></li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Language" %}<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    {% for lang in LANGUAGES %}
                    <form class="form-lang" name="setLang{{ lang.1 }}" action="/i18n/setlang/" method="POST">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ request.path }}" />
                        <input type="hidden" name="language" value="{{ lang.0 }}" />
                        
                        <li>
                            <a rel="nofollow" onclick="document.setLang{{ lang.1 }}.submit();return false;">
                            <img src="/static/img/blank.gif" class="flag flag-{{ lang.0 }}" alt="{{ lang.1 }}" /> {{ lang.1 }}</a>
                        </li>
                    </form>
                  {% endfor %}    
                </ul>
              </li>
          
            {% if user.configured %}
              <li class="divider-vertical"></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a rel="nofollow" href="/config"><i class="icon-user"></i> {% trans "Configure" %}</a></li>
                  <li><a rel="nofollow" href="/done"><i class="icon-th-list"></i> {% trans "Post-tweets" %}</a></li>
                  <li><a rel="nofollow" href="/logout"><i class="icon-off"></i> {% trans "Logout" %}</a></li>
<!--              <li class="divider"></li> -->
                </ul>
              </li>
            </ul>
            {% else %}
              <li class="divider-vertical"></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Login" %}<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url socialauth_begin 'twitter' %}">{% trans "Login with twitter" %}</a></li>
<!--               <li class="divider"></li>  -->
                </ul>
              </li>
            </ul>
            {% endif %}

          <!--</div>--><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
            {% block content %}{% endblock %}
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap-scrollspy.js"></script>
    <script src="/static/js/bootstrap-tab.js"></script>
    <script src="/static/js/bootstrap-tooltip.js"></script>
    <script src="/static/js/bootstrap-popover.js"></script>
    <script src="/static/js/bootstrap-button.js"></script>
    <script src="/static/js/bootstrap-collapse.js"></script>
    <script src="/static/js/bootstrap-carousel.js"></script>
    <script src="/static/js/bootstrap-typeahead.js"></script>
    <script src="/static/js/bootstrap-transition.js"></script>
    <script src="/static/js/bootstrap-alert.js"></script>
    <script src="/static/js/bootstrap-modal.js"></script>
    <script src="/static/js/bootstrap-dropdown.js"></script>
    <script src="/static/js/bootstrap-scrollspy.js"></script>
    {% block script %}{% endblock %}
    
<!--     <script src="/static/js/twitterfriends-0.1.min.js"></script> -->
<!--    <script type="text/javascript">
        function displayunicode(e){
            var unicode=e.keyCode? e.keyCode : e.charCode;
            if(unicode == 50){
                $('#twitterfriends').focus();
            }
        }
    </script>-->
<!--     <script>TwitterFriends.Init('{{user.username}}', $("#id_text"));</script> -->

    {% if new_posttweet %}
        <script type="text/javascript">
        //<![CDATA[
            $(document).ready(function(){
                $('#myModal').modal('show');
            });
        //]]>
        </script>
    {% endif %}

    <script>

        function updateCountdown(textarea,counter) {
            // 140 is the max message length
            var remaining = 140 - $(textarea).val().length;
            $(counter).text(remaining);
            if(remaining < 0){
                $(textarea).val($(textarea).val().substring(0,140));
                updateCountdown(textarea,counter);
            }
        }

        function startCounter(textarea, counter){
            $(document).ready(function() {
                updateCountdown(textarea,counter);
                $(textarea).change( function() { updateCountdown(textarea,counter) } );
                $(textarea).keyup( function() { updateCountdown(textarea,counter) } );
            });
        }

        startCounter('#id_text','#counter');
        startCounter('#id_updatetweet', '#counter2');
    </script>


  </body>
</html>

templates/basemail.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Foowill Mailing</title>

    <!-- Google analitycs -->
    <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32608311-1']);
    _gaq.push(['_trackPageview']);
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    </script>
  </head>


<body>
  <div class="container">
	{% block content %}{% endblock %}
  </div> <!-- /container -->
</body>
</html>

templates/config.html
{% extends "base.html" %}

{% load extras %}
{% load i18n %}

{% block css %}
    <link href="/static/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block script %}
  <script src="/static/js/jquery-ui.min.js"></script>
  <script src="/static/js/slider.js"></script>

  <script>
     $(document).ready(function() {
        /*scale in diferent proportion*/
        trueValues = {% tuple2dict 'ACTIVITY_CHOICES' %}
        values =  [0,1,3,6,9,14,19,24,29,34,39,44,49,55,56,77,89,100];

        trueValues2 = {% tuple2dict 'PUBLISH_CHOICES' %}
        /*Using values to a proportional scale*/
        values2 =  {% values 'PUBLISH_CHOICES' %};

        /*Slider activity_interval*/
        new Slider("#slider_ai","#id_activity_interval",values, trueValues);
        new Slider("#slider_mi","#id_mail_interval",values, trueValues);
        new Slider("#slider_pi","#id_publish_interval",values2, trueValues2);

    });
  </script>
{% endblock %}

{% block content %}
    {% include "user-box.html" %}

    <div class='header-inner'>
        <h2>{% trans 'Settings' %}</h2>
    </div>

<div class='content-box'>
    {% if saved %}
        <div class="alert alert-success">
        {% trans "Settings saved" %}
        </div>
    {% endif %}

    {% if not user.configured %}
        <div class="alert alert-error">
        <h2>{% trans "You need to configure the application" %}</h2>
        </div>
    {% endif %}
        <form action="/config/" method="post" class="form-horizontal"> 

        {% csrf_token %}
        {{ form.non_field_errors }}

            <div class="control-group">
            <label class="control-label" for="email">{% trans 'Email' %}</label>
            <div class="controls">
                {{ form.email }}
                <p class="help-block">
                    {% trans 'We need your email to send you a verification email.' %}<br/>
                    {% trans 'If you leave the field blank, your saved tweets will be posted immediately after reaching the interval of inactivity.' %}
                </p>
                {{ form.email.errors }}
            </div>
            </div>


            <div class="control-group">
            <label class="control-label" for="activity_interval">{% trans 'Interval of inactivity' %}</label>
            <div class="controls">
                <div id="slider_ai" class='slider'></div>
                {{ form.activity_interval }}
                {{ form.activity_interval.errors }}
                <p class="help-block">
                    {% trans 'How long without updating your status should make us worry for you?' %}<br/>
                    {% if user.update_date %}
                        {% trans 'Your last update on twitter was' %} {{ user.last_update|relative_date }}
                    {% endif %}
                </p>
            </div>
            </div>


            <div class="control-group">
            <label class="control-label" for="mail_interval">{% trans 'Time pending verification' %}</label>
            <div class="controls">
                
                <div id="slider_mi" class='slider'></div>	
                {{ form.mail_interval }}
                {{ form.activity_interval.errors }}
                <p class="help-block">{% trans 'How long we wait for the response to verification mail?' %}</p>
            </div>
            </div>

            <div class="control-group">
            <label class="control-label" for="publish_interval">{% trans 'Publish interval' %}</label>
            <div class="controls">
                <div id="slider_pi" class='slider'></div> 
                {{ form.publish_interval }}
                {{ form.activity_interval.errors }}
                <p class="help-block">{% trans 'Interval of time between post-tweets update' %}</p>
            </div>
            </div>

<!--            <div class="control-group">
            <label class="control-label" for="publish_interval">{% trans 'Timezone' %}</label>
            <div class="controls">
            <select name="timezone">
                {% for tz in timezones %}
                <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected="selected"{% endif %}>{{ tz }}</option>
                {% endfor %}
            </select>
            </div>
            </div>-->

            <div class="form-actions">
            <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
            </div>

        </form>

    </div>
</div>
{% endblock %}

templates/contact.html
{% extends "base.html" %}

{% load i18n %}

{% block head %}
<!-- TinyMCE -->
    <script type="text/javascript" src="/static/js/tiny_mce/tiny_mce.js"></script>
    <script type="text/javascript">
            tinyMCE.init({
                    mode : "exact",
                    elements: "id_message",
                    theme : "advanced",
                    plugins : "autolink,fullscreen",
                    // Theme options
                    theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,hr,fullscreen",
                    theme_advanced_toolbar_location : "top",
                    theme_advanced_toolbar_align : "left",
                    theme_advanced_statusbar_location : "bottom",
                    theme_advanced_resizing : true,
            });
    </script>
    <!-- /TinyMCE -->
{% endblock %}

{% block content %}

    {% include "user-box.html" %}

    <div class='main-box'>

    {% if infomail %}
        <div class="alert alert-success">
        {% trans "Message sent, we'll try to reply as soon as possible to the your email address:" %} <b>{{ from_email }}</b>
        </div>
    {% endif %}

    {% if not infomail and sended %}
        <div class="alert alert-alert">
        {% trans "Message unsent. Form errors, correct the fields and try again." %}
        </div>
    {% endif %}

    <div class='contact-form'>


    <form action="" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="control-group">
        <label class="control-label" for="sender">{{form.name.label}}</label>
        <div class="controls">
            {{ form.name }}
            <p class="help-block"></p>
            {% if form.name.errors %}
                <div class="alert alert-error">
                    {{ form.name.errors }}
                </div>
            {% endif %}
        </div>
        </div>

        <div class="control-group">
        <label class="control-label" for="sender">{{form.sender.label}}</label>
        <div class="controls">
            {{ form.sender }}
            <p class="help-block"></p>
            {% if form.sender.errors %}
                <div class="alert alert-error">
                    {{ form.sender.errors }}
                </div>
            {% endif %}
        </div>
        </div>

        <div class="control-group">
        <label class="control-label" for="subject">{{form.subject.label}}</label>
        <div class="controls">
            {{ form.subject }}
            <p class="help-block"></p>
            {% if form.subject.errors %}
                <div class="alert alert-error">
                    {{ form.subject.errors }}
                </div>
            {% endif %}
        </div>
        </div>

        <div class="control-group">
        <label class="control-label" for="message">{{form.message.label}}</label>
        <div class="controls">
            {{ form.message }}
            <p class="help-block"></p>
            {% if form.message.errors %}
                <div class="alert alert-error">
                    {{ form.message.errors }}
                </div>
            {% endif %}
        </div>
        </div>


        <input type="submit" value="{% trans "Send Message" %}" />
    </form>

</div>
</div>
    {% if not user.configured %}
         {% include "footer.html" %}
    {% endif %}
{% endblock %}

templates/done.html
{% extends "base.html" %}

{% load extras %}
{% load i18n %}

{% block content %}
    {% include "modal-newposttweet.html" %}
    {% include "user-box.html" %}

    <div class='header-inner'>
        <h2>Post-tweets</h2>
    </div>

    <div class='content-box'>
        {% for tweet in tweets %}
            <div class='tweet'>
                <p>{% parse_tweet tweet.text %}</p>
                <div class='tweet-info'>
                    <i>{{ tweet.pub_date|relative_date }}</i>
                    <a href="/tweet/delete/{{tweet.pk}}"><i class="icon-trash icon-black"></i> {% trans 'Delete' %}</a><br/>
                </div>
            </div>
        {% endfor %}
    </div>
  </div>

</div>

{% include "modal-newposttweet.html" %}

{% endblock %}

templates/error.html
{% extends "base.html" %}

{% block heading %}Error!{% endblock %}

{% block content %}
<div>
  <p>Sorry but some error made you impossible to login.</p>

  {% if messages %}
    {% for msg in messages %}
        <p class="error">{{ msg.message }} ({{ msg.extra_tags }})</p>
    {% endfor %}
  {% endif %}
  {% if error_msg %}
    <p>Details:</p>
    <p class="error">{{ error_msg }}</p>
  {% endif %}

  <p>Please try again <a href="/">Home</a></p>
</div>
{% endblock %}

templates/footer.html
{% load i18n %}

<div class='footer-box'>
    <a href="https://twitter.com/foo_will">Twitter</a>
    <a href="/about">{% trans "About" %}</a>
    <a href="https://twitter.com/eduherraiz">@eduherraiz</a>
</div>

templates/form.html
{% extends "base.html" %}

{% block heading %}User basic form{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>
        <label for="id_username">Username</label>
        <input type="text" name="username" id="id_username" value="" />
    </p>

    <input type="submit" value="Send" />
</form>
{% endblock %}

templates/modal-newposttweet.html
{% load i18n %}

{% if new_posttweet %}
    <div class="modal hide" id="myModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'Do you want to update your twitter status?' %}</h3>
    </div>
    
    <form action="/update_status/" method="post">
    {% csrf_token %}
        <div class="modal-body">
            {{ updatetweetform.updatetweet }}
            <div id="counter2" ></div>
        </div>
        <div class="modal-footer">
        <input type="submit" class="btn btn-inverse" name="never" value="{% trans 'Never' %}">
        <input type="submit" class="btn btn-danger" name="nottoday" value="{% trans 'Not today' %}">
        <input type="submit" class="btn btn-warning" name="notnow" value="{% trans 'Not now' %}">
        <input type="submit" class="btn btn-success" name="ever" value="{% trans 'Now and ever' %}">
        <input type="submit" class="btn btn-info"  name="now" value="{% trans 'Just now' %}">
        </div>
    </form>
    </div>
{% endif %}
 